export default {
  /*
   *   Request Lists
   */
  GET_LISTS: "GET_LISTS",
  GET_LISTS_SUCCESS: "GET_LISTS_SUCCES",
  GET_LISTS_FAIL: "GET_LISTS_FAIL",

  /*
   *   Create new Item
   * */
  CREATE_ITEM: "CREATE_ITEM",
  CREATE_ITEM_SUCCESS: "CREATE_ITEM_SUCCESS",
  CREATE_ITEM_FAIL: "CREATE_ITEM_FAIL",

  /*
   *   Change Status of a listContainer
   * */
  CHANGE_STATUS: "CHANGE_STATUS",
  CHANGE_STATUS_SUCCESS: "CHANGE_STATUS_SUCCESS",
  CHANGE_STATUS_FAIL: "CHANGE_STATUS_FAIL",

  /*
   * Change Item name
   * */
  CHANGE_NAME: "CHANGE_NAME",
  CHANGE_NAME_SUCCESS: "CHANGE_NAME_SUCCESS",
  CHANGE_NAME_FAIL: "CHANGE_NAME_FAIL",

  /*
   *   Delete Item
   * */
  DELETE_ITEM: "DELETE_ITEM",
  DELETE_ITEM_SUCCESS: "DELETE_ITEM_SUCCESS",
  DELETE_ITEM_FAIL: "DELETE_ITEM_FAIL"
};
